
#############################################################
########## LOCAL Environment ################################
#############################################################
spring:
   profiles: LOCAL
   datasource:
      url: jdbc:mysql://localhost:3306/onlinemess?allowPublicKeyRetrieval=true&useSSL=false
      username: anush
      password: sparks123

server:
   port: 8082
   tomcat:
      max-threads: 500
      max-connections: 500
